In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('../dataset.csv')

In [9]:
df.head()

,movie_id,title,year,directors,actors,genres
0,1,toy story,1995,John Lasseter,Tom Hanks Tim Allen Don Rickles Jim Varney Wal...,Animation Adventure Comedy Family Fantasy
1,2,goldeneye,1995,Martin Campbell,Pierce Brosnan Sean Bean Izabella Scorupco Fam...,Action Adventure Thriller
2,3,four rooms,1995,Allison Anders Alexandre Rockwell Robert Rodri...,Sammi Davis Amanda De Cadenet Valeria Golino M...,Comedy
3,4,get shorty,1995,Barry Sonnenfeld,John Travolta Gene Hackman Rene Russo Danny De...,Comedy Crime Thriller
4,5,copycat,1995,Jon Amiel,Sigourney Weaver Holly Hunter Dermot Mulroney ...,Drama Mystery Thriller

In [12]:
df.shape

(1681, 6)

In [17]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.isna().sum()

movie_id       0
title          0
year           0
directors    126
actors       126
genres       120
dtype: int64

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1681 entries, 0 to 1680
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   movie_id   1681 non-null   int64
 1   title      1681 non-null   str
 2   year       1681 non-null   int64
 3   directors  1555 non-null   str
 4   actors     1555 non-null   str
 5   genres     1561 non-null   str
dtypes: int64(2), str(4)
memory usage: 78.9 KB

In [25]:
df = df.dropna()

In [31]:
df.shape

(1546, 6)

In [32]:
df['soup'] = (
    df['genres'].fillna('') + ' ' +
    df['directors'].fillna('') + ' ' +
    df['actors'].fillna('')
)

In [39]:
df.head()

,movie_id,title,year,directors,actors,genres,soup
0,1,toy story,1995,John Lasseter,Tom Hanks Tim Allen Don Rickles Jim Varney Wal...,Animation Adventure Comedy Family Fantasy,Animation Adventure Comedy Family Fantasy John...
1,2,goldeneye,1995,Martin Campbell,Pierce Brosnan Sean Bean Izabella Scorupco Fam...,Action Adventure Thriller,Action Adventure Thriller Martin Campbell Pier...
2,3,four rooms,1995,Allison Anders Alexandre Rockwell Robert Rodri...,Sammi Davis Amanda De Cadenet Valeria Golino M...,Comedy,Comedy Allison Anders Alexandre Rockwell Rober...
3,4,get shorty,1995,Barry Sonnenfeld,John Travolta Gene Hackman Rene Russo Danny De...,Comedy Crime Thriller,Comedy Crime Thriller Barry Sonnenfeld John Tr...
4,5,copycat,1995,Jon Amiel,Sigourney Weaver Holly Hunter Dermot Mulroney ...,Drama Mystery Thriller,Drama Mystery Thriller Jon Amiel Sigourney Wea...

In [38]:
df['soup'][0]

"Animation Adventure Comedy Family Fantasy John Lasseter Tom Hanks Tim Allen Don Rickles Jim Varney Wallace Shawn John Ratzenberger Annie Potts John Morris Erik von Detten Laurie Metcalf R. Lee Ermey Sarah Freeman Penn Jillette Jack Angel Spencer Aste Greg Berg Lisa Bradley Kendall Cunningham Debi Derryberry Cody Dorkin Bill Farmer Craig Good Gregory Grudt Danielle Judovits Sam Lasseter Brittany Levenbrown Sherry Lynn Scott McAfee Mickie McGowan Ryan O'Donohue Jeff Pidgeon Patrick Pinney Phil Proctor Jan Rabson Joe Ranft Andrew Stanton Shane Sweet Anthony Burch Carole Jeghers John Lasseter Billy West"